name: "notes-backend"
port: ${PORT}
memory: 512M

env:
  NODE_ENV: ${NODE_ENV}
  MONGO_URI: ${MONGO_URI}
  JWT_SECRET: ${JWT_SECRET}

build:
  commands:
    - npm install
    - npm run build

start:
  script: npm start

health_check:
  endpoint: /api/health
  timeout: 30s